# Generated by Django 4.2.2 on 2023-06-17 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_page', '0002_user_name_alter_user_avatar_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
