# Generated by Django 4.2.2 on 2023-06-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_page', '0005_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delay',
            field=models.BooleanField(default=False),
        ),
    ]
