# Generated by Django 4.2.2 on 2023-06-18 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_page', '0006_task_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 54, 41, 976299, tzinfo=datetime.timezone.utc)),
        ),
    ]
