# Generated by Django 4.2.2 on 2023-06-19 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_page', '0007_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 13, 38, 344088)),
        ),
    ]
